#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "book_management.h"
#include "utility.h"
#include "reg_log.h"
#include "users.h"

int main( int argc, char **argv )
{
	BookList *book_all;
	book_all = (BookList *)malloc(sizeof(BookList));
	book_all->list = (Book *)malloc(sizeof(Book));

	UserList *user_all;
	user_all = (UserList *)malloc(sizeof(UserList));
	user_all->list = (User *)malloc(sizeof(User));

	FILE *fp;

	fp = fopen("books.txt", "r");
	if( fp == NULL) {
		printf("\nError, books file does not exist.\n");
		exit(0);
	}
	load_books(fp, book_all);
	fclose(fp);

	fp = fopen("users.txt", "r");
	if( fp == NULL) {
		printf("\nError, users file does not exist.\n");
		exit(0);
	}
	load_users(fp, user_all);
	fclose(fp);

	fp = fopen("loans.txt", "r");
	if( fp == NULL) {
		printf("\nError, loans file does not exist.\n");
		exit(0);
	}
	load_loans(fp);
	fclose(fp);


	int libraryOpen = 1;
	int option;
	while( libraryOpen ){
		printf("\n Please choose an option:\n 1) Register an account\n 2) Login\n 3) Search for books\n 4) Display all books\n 5) Quit\n Option: ");
		option = optionChoice();

		if( option == 1 ) {
			reg(user_all);
		}
		else if( option == 2 ) {
			User *name;
			name = login(user_all);
			if(name == NULL){
				//TODO
			}
			else if(strcmp(name->username, "librarian") == 0){
				librarianCLI(book_all);
			}
			else if(name){
				userCLI(user_all, name);
			}
		}
		else if( option == 3 ) {
			printf("\nLogging search menu...\n");
			searchCLI(book_all);
		}
		else if( option == 4 ) {
			display_all(book_all);
		}
		else if( option == 5 ) {
			libraryOpen = 0;
			printf("\nThank you for using the library!\nGoodbye!\n");
		}
		else
			printf("\nSorry, the option you entered was invalid, please try again.\n");
	}

	//store_books(FILE *file);
	//store_users(FILE *file);
	//store_loans(FILE *file);

	free(book_all);
	free(user_all);

	return 0;
}

int store_books(FILE *file) {

}



//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file, BookList *book_all) {
	Book *p, *last;
	last = book_all->list;
	char StrLine[1024];
	while(!feof(file))
	{
		if(!feof(file)){
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = atoi(StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			strcpy(p->title, StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			strcpy(p->authors, StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p->year = atoi(StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p->copies = atoi(StrLine);
			last->next = p;
			last = p;
			fgets(StrLine, 1024, file);
		}
		else {
			break;
		}
	}
	last->next = NULL;
	return 0;
}



//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book, BookList *book_all) {
	Book *head, *p;
	head = book_all->list;

	while(head->next != NULL){
		head = head->next;
		if(strcmp(head->title, book.title) == 0){
			printf("\nSorry, there is a same book title.\n");
			return 1;
		}
	}
	p = (Book *)malloc(sizeof(Book));
	p->title = (char*)malloc(sizeof(char));
	p->authors = (char*)malloc(sizeof(char));
	strcpy(p->title, book.title);
	strcpy(p->authors, book.authors);
	p->year = book.year;
	p->copies = book.copies;
	p->id = head->id + 1;
	head = book_all->list;
	while(head->next != NULL){
		head = head->next;
	}
	head->next = p;
	p->next = NULL;
	return 0;
}

Book *add_book_input() {
	Book *New;
	New = (Book *)malloc(sizeof(Book));
	char title[99];
	char author[99];
	char year[99];
	char copies[99];
	printf("Enter the title of your book you wish to add: ");
	gets(title);
	printf("Enter the author of your book you wish to add: ");
	gets(author);
	printf("Enter the year that your book you wish to add was released: ");
	gets(year);
	if(atoi(year) == 0){
		printf("\nyear must be a number\n");
		New = NULL;
		return New;
	}
	printf("Enter the the number of copies of your book you wish to add: ");
	gets(copies);
	if(atoi(copies) == 0){
		printf("\ncopies must be a number\n");
		New = NULL;
		return New;
	}

	New->title = (char*)malloc(sizeof(char));
	New->authors = (char*)malloc(sizeof(char));
	strcpy(New->title, title);
	strcpy(New->authors, author);
	New->year = atoi(year);
	New->copies = atoi(copies);
	New->next = NULL;
	return New;
}



//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book, BookList *book_all) {
	display_all(book_all);

}



//finds books with a given title.
//returns a BookList structure, where the field "list" is a list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_title (const char *title, BookList *book_all) {
	Book *head;
	head = book_all->list->next;

	BookList *byTitle;
	byTitle= (BookList *)malloc(sizeof(BookList));
	byTitle->list = (Book *)malloc(sizeof(Book));
	byTitle->length = 0;
	Book *p, *last;
	last = byTitle->list;

	while(head != NULL){
		if(strcmp(head->title, title) == 0){
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = head->id;
			strcpy(p->title, head->title);
			strcpy(p->authors, head->authors);
			p->year = head->year;
			p->id = head->id;
			p->copies = head->copies;
			last->next = p;
			last = p;
			byTitle->length++;
		}
		head = head->next;
	}
	last->next = NULL;
	if(byTitle->length == 0){
		byTitle->list = NULL;
	}

	return *byTitle;
}



//finds books with the given authors.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_author (const char *author, BookList *book_all) {
	Book *head;
	head = book_all->list->next;

	BookList *byAuthor;
	byAuthor= (BookList *)malloc(sizeof(BookList));
	byAuthor->list = (Book *)malloc(sizeof(Book));
	byAuthor->length = 0;
	Book *p, *last;
	last = byAuthor->list;

	while(head != NULL){
		if(strcmp(head->authors, author) == 0){
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = head->id;
			strcpy(p->title, head->title);
			strcpy(p->authors, head->authors);
			p->year = head->year;
			p->id = head->id;
			p->copies = head->copies;
			last->next = p;
			last = p;
			byAuthor->length++;
		}
		head = head->next;
	}
	last->next = NULL;
	if(byAuthor->length == 0){
		byAuthor->list = NULL;
	}

	return *byAuthor;
}



//finds books published in the given year.
//returns a Booklist structure, where the field "list" is a list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_year (unsigned int year, BookList *book_all) {
	Book *head;
	head = book_all->list->next;

	BookList *byYear;
	byYear= (BookList *)malloc(sizeof(BookList));
	byYear->list = (Book *)malloc(sizeof(Book));
	byYear->length = 0;
	Book *p, *last;
	last = byYear->list;

	while(head != NULL){
		if(head->year == year){
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = head->id;
			strcpy(p->title, head->title);
			strcpy(p->authors, head->authors);
			p->year = head->year;
			p->id = head->id;
			p->copies = head->copies;
			last->next = p;
			last = p;
			byYear->length++;
		}
		head = head->next;
	}
	last->next = NULL;
	if(byYear->length == 0){
		byYear->list = NULL;
	}

	return *byYear;
}

void display_found(BookList theBook) {
	Book *head;
	if(theBook.list == NULL){
		printf("\nSorry, no book is found.\n");
	}
	else {
		head = theBook.list->next;
		printf("\n%-5s%-30s%-30s%-10s%-10s\n", "ID", "Title", "Authors", "years", "copies");
		while(head != NULL)
		{
			printf("%-5d%-30s%-30s%-10d%-10d\n", head->id, head->title, head->authors, head->year, head->copies);
			head=head->next;
		}
	}
}

void display_all(BookList *book_all) {
	Book *head;
	head = book_all->list->next;
	printf("\n%-5s%-30s%-30s%-10s%-10s\n", "ID", "Title", "Authors", "years", "copies");
	while(head!=NULL)
	{
		printf("%-5d%-30s%-30s%-10d%-10d\n", head->id, head->title, head->authors, head->year, head->copies);
		head=head->next;
	}
}



void searchCLI(BookList *book_all) {
	int searching = 1;
	int option;
	char *information;
	information = (char*)malloc(sizeof(char)*1024);

	while( searching ){
		printf("\n Please choose an option:\n 1) Find books by title\n 2) Find books by author\n 3) Find books by year\n 4) Return to previews menu\nOption: ");
		option = optionChoice();

		if( option == 1 ) {
			printf("Please enter a title: ");
			gets(information);
			display_found(find_book_by_title(information, book_all));
		}
		else if( option == 2 ) {
			printf("Please enter an author: ");
			gets(information);
			display_found(find_book_by_author(information, book_all));
		}
		else if( option == 3 ) {
			printf("Please enter a year: ");
			gets(information);
			if(atoi(information) == 0){
				printf("the year must be a number.");
			}
			else {
				display_found(find_book_by_year(atoi(information), book_all));
			}
		}
		else if( option == 4 ) {
			searching = 0;
			printf("\nReturn to previews menu...\n");
		}
		else
			printf("\nSorry, the option you entered was invalid, please try again.\n");
	}
	return;
}



int store_users(FILE *file) {

}



int load_users(FILE *file, UserList *user_all) {
	User *p, *last;
	last = user_all->list;
	char StrLine[1024];
	while(!feof(file))
	{
		if(!feof(file)){
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p = (User *)malloc(sizeof(User));
			p->username = (char*)malloc(sizeof(char));
			p->password = (char*)malloc(sizeof(char));
			strcpy(p->username, StrLine);
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			strcpy(p->password, StrLine);
			p->borrow_num = 0;
			
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			if(StrLine[0] != '\0'){
				char *str = StrLine;
				int c, bytesread;
				p->borrow = (Loan *)malloc(sizeof(Loan));
				Loan *pl, *lastl;
				lastl = p->borrow;
				while (sscanf(str, "%d%n", &c, &bytesread) > 0) {
					p->borrow_num ++;
					pl = (Loan *)malloc(sizeof(Loan));
					pl->loan_id = c;
					lastl->next = pl;
					lastl = pl;
					str += bytesread;
				}
				lastl->next = NULL;
			}
			
			
			last->next = p;
			last = p;
			Loan *lastl;
			lastl = last->borrow->next;
			while(lastl != NULL){
				printf("%d", lastl->loan_id);
				lastl = lastl->next;
				
			}
			printf("\n%d", last->borrow_num);
			fgets(StrLine, 1024, file);
		}
		else {
			break;
		}
	}
	last->next = NULL;
	
	return 0;
}



int store_loans(FILE *file) {

}



int load_loans(FILE *file) {

}


int reg(UserList *user_all) {
	char enteredname[30];
	char enteredpass[30];

	User *head, *New;
	head = user_all->list;
	printf("\nPlease enter a username: ");
	gets(enteredname);
	if(strcmp(enteredname, "librarian")==0){
		printf("\nSorry, registration unsuccessful, the username you entered already exists.\n");
		return 1;
	}
	while(head != NULL){
		if(strcmp(head->username, enteredname)==0){
			printf("\nSorry, registration unsuccessful, the username you entered already exists.\n");
			return 1;
		}
		head = head->next;
	}
	printf("\nPlease enter a passward: ");
	gets(enteredpass);
	New = (User *)malloc(sizeof(User));
	New->username = (char*)malloc(sizeof(char));
	New->password = (char*)malloc(sizeof(char));
	strcpy(New->username, enteredname);
	strcpy(New->password, enteredpass);
	head = user_all->list;
	while(head->next != NULL){
		head = head->next;
	}
	head->next = New;
	New->next = NULL;

	printf("\nRegistered library account successfully!\n");
}



User *login(UserList *user_all) {
	char enteredname[30];
	char enteredpass[30];
	char password[30];
	User *head;
	head = user_all->list->next;

	printf("\nPlease enter a username: ");
	gets(enteredname);
	if(strcmp(enteredname, "librarian") == 0){
		strcpy(password, "librarian");
	}
	else if(1){
		while(head != NULL){
			if(strcmp(head->username, enteredname)==0){
				strcpy(password, head->password);
				break;
			}
			head = head->next;
		}
	}
	else {
		printf("\nUsername does not exist.\n");
		return NULL;
	}
	printf("\nPlease enter a passward: ");
	gets(enteredpass);
	if(strcmp(enteredpass, password) == 0){
		return head;
	}
	else {
		printf("\nWrong password.\n");
	}
	return NULL;
}


void librarianCLI(BookList *book_all) {
	int librarianLoggedIn = 1;
	int option;
	Book *book;

	while( librarianLoggedIn ){
		printf("\n Please choose an option:\n 1) Add a book\n 2) Remove a book\n 3) Search for books\n 4) Display all books\n 5) Log out\n Option: ");
		option = optionChoice();

		if( option == 1 ) {
			book = add_book_input();
			if(book != NULL) {
				add_book(*book, book_all);
			}
		}
		else if( option == 2 ) {
			remove_book(*book, book_all);
		}
		else if( option == 3 ) {
			searchCLI(book_all);
		}
		else if( option == 4 ) {
			display_all(book_all);
		}
		else if( option == 5 ) {
			librarianLoggedIn = 0;
			printf("\nLogging out...\n");
		}
		else
			printf("\nSorry, the option you entered was invalid, please try again.\n");
	}
	return;
}

void userCLI(UserList *user_all, User *name) {
	int userLoggedIn = 1;
	int option;

	while( userLoggedIn ){
		printf("\n(logged in as: %s)", name->username);
		printf("\n Please choose an option:\n 1) Borrow a book\n 2) Return a book\n 3) Search for books\n 4) Display all books\n 5) Log out\n Option: ");
		option = optionChoice();

		if( option == 1 ) {

		}
		else if( option == 2 ) {

		}
		else if( option == 3 ) {
			printf("\nLibrarian login\n");
		}
		else if( option == 4 ) {
			printf("\nLibrarian login\n");
		}
		else if( option == 5 ) {
			userLoggedIn = 0;
			printf("\nLogging out...\n");
		}
		else
			printf("\nSorry, the option you entered was invalid, please try again.\n");
	}
	return;
}


int optionChoice( void ) {
	int option = -1;
	char line[80];

	// read in the current line as a string
	fgets(line,80,stdin);

	// atoi() converts string to integer, returns 0 if could not convert
	option = (int)atoi(line);

	return option;
}

// remove newline character from the fgets() input

void removeNewLine(char* string) {

	size_t length = strlen(string);

	if((length > 0) && (string[length-1] == '\n')) {
		string[length-1] ='\0';
	}
	return;
}
