#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "book_management.h"
#include "utility.h"

#define CreateNode(p)  p=(Book *)malloc(sizeof(Book));
#define DeleteNode(p)   free((void *)p);




//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file) {

}



//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file, BookList *book_all) {
	Book *p, *last;
	last = book_all->list;
	char StrLine[1024];
	while(!feof(file))
	{
		if(!feof(file)){
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = atoi(StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			strcpy(p->title, StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			strcpy(p->authors, StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p->year = atoi(StrLine);

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p->copies = atoi(StrLine);
			p->borrowed_copies = 0;

			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p->borrow = (Loan *)malloc(sizeof(Loan));
			if(StrLine[0] != '\0'){
				char *str = StrLine;
				int bytesread;
				char c[1024];
				Loan *pl, *lastl;
				lastl = p->borrow;
				while (sscanf(str, "%s%n", &c, &bytesread) > 0) {
					p->borrowed_copies ++;
					pl = (Loan *)malloc(sizeof(Loan));
					pl->loan_user = (char*)malloc(sizeof(char));
					strcpy(pl->loan_user, c);
					lastl->next = pl;
					lastl = pl;
					str += bytesread;
				}
				lastl->next = NULL;
			}

			last->next = p;
			last = p;
			fgets(StrLine, 1024, file);
		}
		else {
			break;
		}
	}
	last->next = NULL;
	last = book_all->list->next;
	while(last != NULL){
		if(last->borrowed_copies > 0){
			Loan *lastl;
			lastl = last->borrow->next;
			while(lastl != NULL){
				printf("\n%s\n", lastl->loan_user);
				lastl = lastl->next;
			}
		}
		last = last->next;
	}
	return 0;
}



//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book, BookList *book_all) {
	Book *head, *p;
	head = book_all->list;

	while(head->next != NULL){
		head = head->next;
		if(strcmp(head->title, book.title) == 0){
			printf("\nSorry, there is a same book title.\n");
			return 1;
		}
	}
	p = (Book *)malloc(sizeof(Book));
	p->title = (char*)malloc(sizeof(char));
	p->authors = (char*)malloc(sizeof(char));
	strcpy(p->title, book.title);
	strcpy(p->authors, book.authors);
	p->year = book.year;
	p->copies = book.copies;
	p->id = head->id + 1;
	head = book_all->list;
	while(head->next != NULL){
		head = head->next;
	}
	head->next = p;
	p->next = NULL;
	return 0;
}

Book *add_book_input() {
	Book *New;
	New = (Book *)malloc(sizeof(Book));
	char title[99];
	char author[99];
	char year[99];
	char copies[99];
	printf("Enter the title of your book you wish to add: ");
	gets(title);
	printf("Enter the author of your book you wish to add: ");
	gets(author);
	printf("Enter the year that your book you wish to add was released: ");
	gets(year);
	if(atoi(year) == 0){
		printf("\nyear must be a number\n");
		New = NULL;
		return New;
	}
	printf("Enter the the number of copies of your book you wish to add: ");
	gets(copies);
	if(atoi(copies) == 0){
		printf("\ncopies must be a number\n");
		New = NULL;
		return New;
	}

	New->title = (char*)malloc(sizeof(char));
	New->authors = (char*)malloc(sizeof(char));
	strcpy(New->title, title);
	strcpy(New->authors, author);
	New->year = atoi(year);
	New->copies = atoi(copies);
	New->next = NULL;
	return New;
}



//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book, BookList *book_all) {
	Book *head, *before, *change;
	head = book_all->list->next;
	before = book_all->list;
	while(head != NULL){
		if(head->id == book.id){
			if(head == book_all->list->next){
				book_all->list->next = head->next;
			}
			else {
				before->next = head->next;
			}
			change = head->next;
			while(change != NULL){
				change->id --;
				change = change->next;
			}
			free(head);
			printf("\nYou have successfully removed the book!\n");
			return 0;
		}
		head = head->next;
		before = before->next;
	}
	printf("\nSorry, the option you entered was invalid, please try again.\n");
	return 1;

}

Book *remove_book_input() {
	Book *theBook;
	theBook = (Book *)malloc(sizeof(Book));
	char id[1024];
	printf("\nEnter the ID number of the book you wish to remove: ");
	gets(id);
	if(atoi(id) == 0){
		printf("\nyear must be a number\n");
		theBook = NULL;
		return theBook;
	}
	theBook->id = atoi(id);
	theBook->next = NULL;
	return theBook;
}



//finds books with a given title.
//returns a BookList structure, where the field "list" is a list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_title (const char *title, BookList *book_all) {
	Book *head;
	head = book_all->list->next;

	BookList *byTitle;
	byTitle= (BookList *)malloc(sizeof(BookList));
	byTitle->list = (Book *)malloc(sizeof(Book));
	byTitle->length = 0;
	Book *p, *last;
	last = byTitle->list;

	while(head != NULL){
		if(strcmp(head->title, title) == 0){
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = head->id;
			strcpy(p->title, head->title);
			strcpy(p->authors, head->authors);
			p->year = head->year;
			p->id = head->id;
			p->copies = head->copies;
			last->next = p;
			last = p;
			byTitle->length++;
		}
		head = head->next;
	}
	last->next = NULL;
	if(byTitle->length == 0){
		byTitle->list = NULL;
	}

	return *byTitle;
}



//finds books with the given authors.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_author (const char *author, BookList *book_all) {
	Book *head;
	head = book_all->list->next;

	BookList *byAuthor;
	byAuthor= (BookList *)malloc(sizeof(BookList));
	byAuthor->list = (Book *)malloc(sizeof(Book));
	byAuthor->length = 0;
	Book *p, *last;
	last = byAuthor->list;

	while(head != NULL){
		if(strcmp(head->authors, author) == 0){
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = head->id;
			strcpy(p->title, head->title);
			strcpy(p->authors, head->authors);
			p->year = head->year;
			p->id = head->id;
			p->copies = head->copies;
			last->next = p;
			last = p;
			byAuthor->length++;
		}
		head = head->next;
	}
	last->next = NULL;
	if(byAuthor->length == 0){
		byAuthor->list = NULL;
	}

	return *byAuthor;
}



//finds books published in the given year.
//returns a Booklist structure, where the field "list" is a list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_year (unsigned int year, BookList *book_all) {
	Book *head;
	head = book_all->list->next;

	BookList *byYear;
	byYear= (BookList *)malloc(sizeof(BookList));
	byYear->list = (Book *)malloc(sizeof(Book));
	byYear->length = 0;
	Book *p, *last;
	last = byYear->list;

	while(head != NULL){
		if(head->year == year){
			p = (Book *)malloc(sizeof(Book));
			p->title = (char*)malloc(sizeof(char));
			p->authors = (char*)malloc(sizeof(char));
			p->id = head->id;
			strcpy(p->title, head->title);
			strcpy(p->authors, head->authors);
			p->year = head->year;
			p->id = head->id;
			p->copies = head->copies;
			last->next = p;
			last = p;
			byYear->length++;
		}
		head = head->next;
	}
	last->next = NULL;
	if(byYear->length == 0){
		byYear->list = NULL;
	}

	return *byYear;
}



//finds books with the given borrower.
//returns a Booklist structure, where the field "list" is a newly allocated list of books, or null if no book with the
//provided title can be found. The length of the list is also recorded in the returned structure, with 0 in case
//list is the NULL pointer.
BookList find_book_by_borrower (const char *borrower, BookList *book_all) {
	Book *head;
	head = book_all->list->next;
	
	BookList *byBorrower;
	byBorrower = (BookList *)malloc(sizeof(BookList));
	byBorrower->list = (Book *)malloc(sizeof(Book));
	byBorrower->length = 0;
	Book *p, *last;
	last = byBorrower->list;
	
	Loan *headl;
	
	while(head != NULL){
		if(head->borrowed_copies > 0){
			headl = head->borrow->next;
			while(headl != NULL){
				if(strcmp(headl->loan_user, borrower) == 0){
					p = (Book *)malloc(sizeof(Book));
					p->title = (char*)malloc(sizeof(char));
					p->authors = (char*)malloc(sizeof(char));
					p->id = head->id;
					strcpy(p->title, head->title);
					strcpy(p->authors, head->authors);
					p->year = head->year;
					p->id = head->id;
					p->copies = head->copies;
					last->next = p;
					last = p;
					byBorrower->length++;
					break;
				}
				headl = headl->next;
			}
		}
		head = head->next;
	}

	last->next = NULL;
	if(byBorrower->length == 0){
		byBorrower->list = NULL;
	}
	
	return *byBorrower;
}



void display_found(BookList theBook) {
	Book *head;
	if(theBook.list == NULL){
		printf("\nSorry, no book is found.\n");
	}
	else {
		head = theBook.list->next;
		printf("\n%-5s%-30s%-30s%-10s%-10s\n", "ID", "Title", "Authors", "years", "copies");
		while(head != NULL)
		{
			printf("%-5d%-30s%-30s%-10d%-10d\n", head->id, head->title, head->authors, head->year, head->copies);
			head=head->next;
		}
	}
}

void display_all(BookList *book_all) {
	Book *head;
	head = book_all->list->next;
	printf("\n%-5s%-30s%-30s%-10s%-10s\n", "ID", "Title", "Authors", "years", "copies");
	while(head!=NULL)
	{
		printf("%-5d%-30s%-30s%-10d%-10d\n", head->id, head->title, head->authors, head->year, head->copies);
		head=head->next;
	}
}



void searchCLI(BookList *book_all) {
	int searching = 1;
	int option;
	char *information;
	information = (char*)malloc(sizeof(char)*1024);

	while( searching ){
		printf("\n Please choose an option:\n 1) Find books by title\n 2) Find books by author\n 3) Find books by year\n 4) Return to previews menu\nOption: ");
		option = optionChoice();

		if( option == 1 ) {
			printf("Please enter a title: ");
			gets(information);
			display_found(find_book_by_title(information, book_all));
		}
		else if( option == 2 ) {
			printf("Please enter an author: ");
			gets(information);
			display_found(find_book_by_author(information, book_all));
		}
		else if( option == 3 ) {
			printf("Please enter a year: ");
			gets(information);
			if(atoi(information) == 0){
				printf("the year must be a number.");
			}
			else {
				display_found(find_book_by_year(atoi(information), book_all));
			}
		}
		else if( option == 4 ) {
			searching = 0;
			printf("\nReturn to previews menu...\n");
		}
		else
			printf("\nSorry, the option you entered was invalid, please try again.\n");
	}
	return;
}



int store_users(FILE *file) {

}



int load_users(FILE *file, UserList *user_all) {
	User *p, *last;
	last = user_all->list;
	char StrLine[1024];
	while(!feof(file))
	{
		if(!feof(file)){
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			p = (User *)malloc(sizeof(User));
			p->username = (char*)malloc(sizeof(char));
			p->password = (char*)malloc(sizeof(char));
			strcpy(p->username, StrLine);
			fgets(StrLine, 1024, file);
			removeNewLine(StrLine);
			strcpy(p->password, StrLine);

			last->next = p;
			last = p;
			fgets(StrLine, 1024, file);
		}
		else {
			break;
		}
	}
	last->next = NULL;

	return 0;
}

